# Generated by `rjournal_pdf_article()` using `knitr::purl()`: do not edit by hand
# Please edit nowcast.Rmd to modify this file

## ----setup, include = FALSE---------------------------------------------------
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE,
                      fig.align = "center", out.width = "100%",
                      fig.pos = "H", out.extra = "")


## ----ragged, fig.cap = "Availability heatmap of four US monthly indicators over the last 24 months. Blue tiles mark months with published observations, grey tiles mark months where the series has not yet been released. The jagged right edge at the most recent dates is the problem \\texttt{nc\\_align()} solves: retail sales, industrial production, payrolls, and sentiment all have different publication lags.", fig.alt = "A heatmap with four rows (retail sales, industrial production, nonfarm payrolls, consumer sentiment) and 24 columns (months). Blue tiles indicate months with published observations; grey tiles indicate months not yet released. The right edge is jagged: sentiment extends furthest, payrolls and retail sales end one month earlier, industrial production two months earlier. This illustrates the ragged-edge publication pattern."----
knitr::include_graphics("figures/fig1_ragged_edge.pdf")


## ----backtest, fig.cap = "Pseudo-real-time bridge-equation nowcast of quarterly US real GDP growth, 2012 onwards. Grey solid line is the realised log-difference of real GDP from FRED series \\texttt{GDPC1}. Blue dashed line is the one-step-ahead nowcast from \\texttt{nc\\_backtest()} with four monthly indicators aggregated to quarterly frequency. Nowcast RMSE over the evaluation window is 0.95 percentage points, MAE is 0.51, bias is 0.03.", fig.alt = "A time-series line chart from 2012 to the mid-2020s. A grey solid line shows realised quarterly US real GDP log-differences; a blue dashed line shows the one-step-ahead bridge-equation nowcast. Both series move together through the period, with the steepest downward spike in 2020 followed by a symmetric recovery. The nowcast closely tracks the realised series outside of the pandemic quarters."----
knitr::include_graphics("figures/fig2_backtest.pdf")


## ----coeffs, fig.cap = "Bridge-equation coefficients for four monthly indicators, full-sample fit. Points are ordinary-least-squares estimates; horizontal bars are 95 per cent confidence intervals. Vertical line at zero marks no effect. Retail sales and industrial production dominate; payrolls and sentiment contribute marginally in this specification.", fig.alt = "A horizontal dot-whisker plot showing four coefficient estimates for retail sales, industrial production, nonfarm payrolls, and consumer sentiment. Retail sales and industrial production have the largest positive point estimates and tightest confidence intervals. Payrolls and sentiment have smaller estimates with wider intervals that straddle zero. A vertical reference line at zero is shown."----
knitr::include_graphics("figures/fig4_coefficients.pdf")


## ----window, fig.cap = "Nowcast error (nowcast minus realised) from expanding-window and rolling-window backtests of the same bridge-equation specification. Expanding window (blue, solid) uses all prior data at each step; rolling window (red, dashed) uses the preceding 40 quarters only. Both peak around the 2020 pandemic contraction; the rolling specification is more responsive afterwards.", fig.alt = "A time-series line chart of nowcast errors over the evaluation window. A blue solid line is the expanding-window error; a red dashed line is the rolling-window error. Both trace near zero through most of the sample with a large positive spike around 2020. The rolling window returns toward zero more quickly after the spike than the expanding window."----
knitr::include_graphics("figures/fig3_window.pdf")


## ----dm, fig.cap = "Diebold-Mariano comparison of two bridge-equation specifications on US GDP. Bars show backtest RMSE. Left: bridge with an AR(1) term. Right: bridge without. The HLN-corrected Diebold-Mariano test statistic and p-value are reported in the annotation box. The test fails to reject the null of equal predictive accuracy.", fig.alt = "A two-bar chart comparing the RMSE of two bridge-equation specifications on US GDP. The left bar is the specification with an AR(1) term; the right bar is the specification without. Both bars are nearly identical in height, near 0.95 percentage points. An annotation box reports the HLN-corrected DM statistic and a p-value above conventional significance thresholds."----
knitr::include_graphics("figures/fig5_dm.pdf")


## ----metrics------------------------------------------------------------------
metrics_tbl <- data.frame(
  Specification = c("Naive AR(1) on target only (benchmark)",
                    "Bridge + AR(1), all four indicators",
                    "Bridge no AR, all four indicators",
                    "Bridge + AR(1), retail + INDPRO only"),
  RMSE = c(1.751, 0.950, 0.974, 1.827),
  MAE  = c(0.734, 0.509, 0.501, 0.743),
  Bias = c(-0.148, 0.025, 0.081, -0.201)
)
knitr::kable(metrics_tbl,
             caption = "Backtest metrics for three bridge-equation specifications on US real GDP growth. Expanding window, first evaluation at quarter forty, 2012-present evaluation sample. Adding the AR(1) term marginally reduces RMSE; dropping two of the four indicators modestly widens it.",
             booktabs = TRUE,
             digits = 3)

